import { renderUsage } from "../output.js";
import { currentHost, currentDistribution, distributionPackageName, distributionBinName } from "../runtime-context.js";
// `superbee hook install|status|uninstall` — manage the SessionStart board-aware hook.
//
// The installed hook runs `<bin> session-start` — ONE subcommand doing a
// time-boxed best-effort board pull and THEN rendering the home view (identity + auth + bundle
// dashboard + board awareness) as ambient context, so an agent orients — with its teammates'
// board changes already pulled — before its first action. It is a single unconditional hook
// command, never two entries or a compound shell string.
//
// MULTI-RUNTIME (AXI §7 "default app targets"): install writes a real SessionStart hook for ALL of
//   • Claude Code   → project .claude/ or ${CLAUDE_CONFIG_DIR:-~/.claude}
//   • Codex         → project .codex/ or ${CODEX_HOME:-~/.codex}
//   • OpenCode      → project .config/opencode/ or its configured/XDG user config directory
//
// Persistent installs launch an absolute CLI entry through an absolute Node executable. For the
// npm channel both paths are proven under the durable global npm prefix, so GUI hosts do not need
// Homebrew/npm on their PATH and the command survives version directory changes. The TOML edit
// reuses the SDK's exported pure updater
// (`computeCodexConfigUpdate`); the JSON SessionStart edit is OUR SDK-modeled pure updater
// (`computeSessionStartHookInstall`) because the SDK's substring marker can claim foreign commands
// and cannot express the full historical compatibility set. The OpenCode plugin source is OURS
// (the SDK's generated plugin spawns its command with NO argv, so it cannot express the launch),
// and its exact generated bytes — never marker presence alone — establish ownership.
//
// DESTRUCTIVE-WRITE DISCIPLINE: `install` REFUSES (structured RUNTIME failure, nothing written)
// any settings file it cannot faithfully round-trip — unparseable JSON or a malformed hooks shape
// — because "repairing" it would destroy the user's other settings. Every managed write goes
// through same-directory temp + rename, so a concurrent reader never observes a torn file.
// Read-only paths (status, probes) and uninstall stay lenient: a malformed file is never touched.
//
// SCOPE: `--scope project` (default) targets the current repo; `--scope user` targets each
// host's configured user directory. Project-scope OpenCode stays under `<cwd>/.config/opencode/`.
import {
  existsSync,
  linkSync,
  lstatSync,
  readlinkSync,
  readFileSync,
  renameSync,
  rmSync,
  symlinkSync,
} from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { isAbsolute, join, normalize, sep } from "node:path";
import { parseArgs } from "node:util";
import {
  computeCodexConfigUpdate,
  type HookSettings,
  type HookEntry,
} from "axi-sdk-js";
import { cliInvocation, collapseHomeDirectory, hookCommand } from "../invocation.js";
import { render, resolveMode } from "../output.js";
import { CliError } from "../errors.js";
import { parseSelectorOrUsage } from "../args.js";
import { CLI_LEAVES } from "../command-spec.js";
import {
  HOST_CONFIG_ROOTS,
  resolveHostConfigRoot,
  resolveOpenCodeConfigRoot,
} from "../host-config.js";
import { atomicWriteFileSync, capturePrivateConfigParent } from "../private-config-write.js";
import {
  classifyHookCommand,
  classifyHookEntry,
  isOwnedHookCompatibility,
  renderGeneratedHookToken,
  tokenizeGeneratedHookCommand,
  type HookCompatibility,
} from "../hook-compatibility.js";
import {
  resolvePersistentInstallAuthority,
  type PersistentInstallAuthority,
} from "../install-authority.js";
import { normalizeInstallScope, type InstallScope } from "../install-scope.js";
import { readRegularFileTextNoFollowSync } from "../nofollow-read.js";
import { inspectHookLaunchAvailability, type HookLaunchAvailability } from "../hook-launch-availability.js";
import { integrationChangeReceipt, type IntegrationHost } from "../integration-receipt.js";

export const HOOK_USAGE = `superbee hook — manage the SessionStart board-aware hook

Usage:
  superbee hook install   [--scope project|user] [--turn-end-sync [--git-boards]]
  superbee hook status    [--scope project|user]
  superbee hook uninstall [--scope project|user] [--turn-end-sync]

Installs (or removes) a SessionStart hook that runs \`session-start\` — a time-boxed best-effort
board pull, then the home view — as ambient context at the start of every agent session, for
Claude Code, Codex, AND OpenCode. Idempotent: re-installing the same hook is a no-op; uninstalling
an absent hook is a no-op. Re-run install after upgrading from a pre-session-start version: the
old hook rendered the home view without pulling the board first.

For npm distribution, install must run from a verified global install (\`npm install -g
superbee\`). One-off npx execution remains supported for read-only/trial commands but cannot
authorize persistent host configuration.

In a hosted checkout (made by \`checkout\`), session-start pulls from the host instead of a board.

End-of-turn sync is a separate opt-in: \`hook install --turn-end-sync\` also installs a Stop hook
that runs \`turn-end\` (one sync of a hosted checkout when the agent's turn ends; nothing anywhere
else) for Claude Code and Codex. OpenCode has no Stop hook, so there it is not installed.
A Git board is never synced by the Stop hook unless you also pass \`--git-boards\`: then the
shared board the session is in is synced (committed, pulled, pushed) at turn end as well.
\`hook install --turn-end-sync\` without it switches the Git sync back off; a plain \`hook install\`
keeps whatever the Stop hook already does.
\`hook uninstall --turn-end-sync\` removes only the Stop hook; plain \`hook uninstall\` removes both.
SUPERBEE_NO_TURN_SYNC=<any value> turns the Stop hook off without uninstalling it, and
SUPERBEE_NO_AUTOPULL=<any value> turns off the automatic hosted pulls (reads and session start).

Options:
  --turn-end-sync   install: also install the end-of-turn Stop hook; uninstall: remove only it
  --git-boards      With install --turn-end-sync: the Stop hook also syncs a shared Git board
  --scope project   Write to the CURRENT project (default): .claude/, .codex/, .config/opencode/
  --scope user      Write to each host's configured user home (environment override or default)
  --json            Emit compact JSON instead of TOON
  -h, --help        Show this help

The former spelling --scope global remains accepted as an alias for --scope user.
`;

/** The canonical OpenCode marker. Marker presence alone never establishes ownership. */
export const HOOK_MARKER = "superbee";
const LEGACY_HOOK_MARKER = "agentstate-lite";

/** Backward-compatible command-only ownership predicate, now backed by the exact token classifier. */
export function isManagedHookCommand(command: string, platform: string = process.platform): boolean {
  return isOwnedHookCompatibility(classifyHookCommand(command, platform));
}
/** SessionStart hook timeout, in seconds (matches the SDK default; session-start budgets under it). */
export const HOOK_TIMEOUT_SECONDS = 10;
/** The pull-then-render subcommand the installed hook runs. */
export const HOOK_SUBCOMMAND = "session-start";
/** The end-of-turn subcommand the opt-in Stop hook runs. */
export const TURN_END_SUBCOMMAND = "turn-end";
/** The turn-end flag that also syncs a shared Git board: Git is opt-in, never the default. */
export const TURN_END_GIT_BOARDS_FLAG = "--git-boards";
/** Stop hook timeout, in seconds: above turn-end's own 20-second sync budget. */
export const TURN_END_HOOK_TIMEOUT_SECONDS = 30;
/** The OpenCode plugin filename (SDK naming convention for this marker) and its managed-file marker. */
const OPENCODE_PLUGIN_FILENAME = "axi-superbee.js";
const LEGACY_OPENCODE_PLUGIN_FILENAME = "axi-agentstate-lite.js";
const OPENCODE_MANAGED_MARKER = `axi-sdk-js managed opencode plugin: ${HOOK_MARKER}`;
const LEGACY_OPENCODE_MANAGED_MARKER = `axi-sdk-js managed opencode plugin: ${LEGACY_HOOK_MARKER}`;

/**
 * Compose one generated shell command from an argv vector. Values outside the deliberately safe
 * unquoted character set use POSIX single-argument quoting; OpenCode receives the same vector
 * directly and never invokes a shell.
 *
 * Writer/recognizer contract, asserted HERE in the owning composer: the composed command must
 * satisfy {@link isManagedHookCommand}, or install would write an ORPHAN hook — invisible to
 * status, duplicated by reinstall, stranded by uninstall. An exotic/future channel outside the
 * explicit grammar fails closed here.
 */
export function sessionStartHookCommand(
  base: string = hookCommand(),
  args: string[] = [HOOK_SUBCOMMAND],
  platform: string = process.platform,
): string {
  const command = [base, ...args].map((token) => renderGeneratedHookToken(token, platform)).join(" ");
  if (!isManagedHookCommand(command, platform)) {
    throw new Error(
      `composed hook command ${JSON.stringify(command)} would not be recognized as managed — refusing to install an orphan hook`,
    );
  }
  return command;
}

/**
 * The Stop hook's command: the SessionStart launch with `turn-end` as its subcommand. A command is
 * ours exactly when it ends in `turn-end` and the same launch ending in `session-start` is a
 * recognized generated SessionStart command, so both hooks share one ownership rule.
 */
export function turnEndHookCommand(
  launch: HookLaunchSpec,
  platform: string = process.platform,
  options: { gitBoards?: boolean } = {},
): string {
  const args = [...launch.args.slice(0, -1), TURN_END_SUBCOMMAND, ...(options.gitBoards ? [TURN_END_GIT_BOARDS_FLAG] : [])];
  const command = [launch.program, ...args].map((token) => renderGeneratedHookToken(token, platform)).join(" ");
  if (!isManagedTurnEndCommand(command, platform)) {
    throw new Error(`composed turn-end hook command ${JSON.stringify(command)} would not be recognized as managed`);
  }
  return command;
}

/** The managed turn-end command's tokens up to and including `turn-end`, and whether it opts in to Git boards. */
function managedTurnEndTokens(command: string, platform: string): { tokens: string[]; gitBoards: boolean } | null {
  const all = tokenizeGeneratedHookCommand(command, platform);
  if (!all) return null;
  const gitBoards = all.at(-1) === TURN_END_GIT_BOARDS_FLAG;
  const tokens = gitBoards ? all.slice(0, -1) : all;
  if (tokens.length < 2 || tokens.at(-1) !== TURN_END_SUBCOMMAND) return null;
  return { tokens, gitBoards };
}

export function isManagedTurnEndCommand(command: string, platform: string = process.platform): boolean {
  const managed = managedTurnEndTokens(command, platform);
  if (!managed) return false;
  const sessionStart = [...managed.tokens.slice(0, -1), HOOK_SUBCOMMAND].map((token) => renderGeneratedHookToken(token, platform)).join(" ");
  return isManagedHookCommand(sessionStart, platform);
}

function isManagedTurnEndHook(hook: HookEntry | undefined): boolean {
  return hook?.type === "command" && typeof hook.command === "string" && isManagedTurnEndCommand(hook.command);
}

/** True when an installed managed Stop hook also syncs Git boards (`turn-end --git-boards`). */
export function turnEndHookSyncsGitBoards(settings: HookSettings, platform: string = process.platform): boolean {
  const stop = settings.hooks?.Stop;
  return Array.isArray(stop) && (stop as HookGroupLike[]).some(
    (group) => Array.isArray(group?.hooks) && group.hooks.some(
      (h) => isManagedTurnEndHook(h) && managedTurnEndTokens(h.command!, platform)?.gitBoards === true,
    ),
  );
}

type HookGroupLike = { matcher?: unknown; hooks?: HookEntry[] };

/** Why a settings file's `hooks.Stop` cannot be edited faithfully, or null. */
function stopShapeProblem(settings: HookSettings): string | null {
  const stop = settings.hooks?.Stop;
  if (stop === undefined) return null;
  if (!Array.isArray(stop)) return "`hooks.Stop` exists but is not an array";
  for (const [i, group] of (stop as unknown[]).entries()) {
    if (!isPlainObject(group)) return `\`hooks.Stop[${i}]\` is not an object`;
    if (group.hooks !== undefined && !Array.isArray(group.hooks)) return `\`hooks.Stop[${i}].hooks\` exists but is not an array`;
  }
  return null;
}

/** Pure install of the managed Stop hook: one entry, rewritten in place, duplicates dropped. */
export function computeTurnEndHookInstall(settings: HookSettings, spec: { command: string; timeoutSeconds?: number }): [HookSettings, boolean] {
  const updated = structuredClone(settings);
  const hooks = (updated.hooks ??= {});
  let changed = settings.hooks === undefined;
  const timeout = spec.timeoutSeconds ?? TURN_END_HOOK_TIMEOUT_SECONDS;
  const groups = (Array.isArray(hooks.Stop) ? hooks.Stop : []) as HookGroupLike[];
  if (!Array.isArray(hooks.Stop)) changed = true;
  let rewritten = false;
  const next: HookGroupLike[] = [];
  for (const group of groups) {
    if (!Array.isArray(group?.hooks)) {
      next.push(group);
      continue;
    }
    const kept: HookEntry[] = [];
    for (const h of group.hooks) {
      if (!isManagedTurnEndHook(h)) {
        kept.push(h);
        continue;
      }
      if (rewritten) {
        changed = true;
        continue;
      }
      rewritten = true;
      if (h.command !== spec.command || h.timeout !== timeout) {
        changed = true;
        h.command = spec.command;
        h.timeout = timeout;
      }
      kept.push(h);
    }
    if (kept.length !== group.hooks.length) {
      if (kept.length === 0) continue;
      group.hooks = kept;
    }
    next.push(group);
  }
  if (!rewritten) {
    next.push({ hooks: [{ type: "command", command: spec.command, timeout }] });
    changed = true;
  }
  hooks.Stop = next as typeof hooks.SessionStart;
  return changed ? [updated, true] : [settings, false];
}

/** Pure removal of every managed Stop hook; foreign hooks and groups survive untouched. */
export function computeTurnEndHookUninstall(settings: HookSettings): [HookSettings, boolean] {
  const stop = settings.hooks?.Stop;
  if (!Array.isArray(stop)) return [settings, false];
  const updated = structuredClone(settings);
  let changed = false;
  const next: HookGroupLike[] = [];
  for (const group of updated.hooks!.Stop as HookGroupLike[]) {
    if (!Array.isArray(group?.hooks)) {
      next.push(group);
      continue;
    }
    const kept = group.hooks.filter((h) => !isManagedTurnEndHook(h));
    if (kept.length !== group.hooks.length) {
      changed = true;
      if (kept.length === 0) continue;
      next.push({ ...group, hooks: kept });
    } else next.push(group);
  }
  if (!changed) return [settings, false];
  if (next.length === 0) delete updated.hooks!.Stop;
  else updated.hooks!.Stop = next as NonNullable<HookSettings["hooks"]>["SessionStart"];
  return [updated, true];
}

/** `hook status`'s end-of-turn report: per host, and which hosts also sync Git boards (only when any does). */
function turnEndStatus(claude: HookSettings, codex: HookSettings): Record<string, unknown> {
  const git = { claude_code: turnEndHookSyncsGitBoards(claude), codex: turnEndHookSyncsGitBoards(codex) };
  return {
    claude_code: turnEndHookInstalled(claude),
    codex: turnEndHookInstalled(codex),
    ...(git.claude_code || git.codex ? { git_boards: git } : {}),
  };
}

/** True when the managed Stop hook is installed in this settings file. */
export function turnEndHookInstalled(settings: HookSettings): boolean {
  const stop = settings.hooks?.Stop;
  return Array.isArray(stop) && (stop as HookGroupLike[]).some((group) => Array.isArray(group?.hooks) && group.hooks.some(isManagedTurnEndHook));
}

export interface HookLaunchSpec {
  program: string;
  args: string[];
  command: string;
}

/** Build the one argv-safe launch shared by shell-string hosts and the OpenCode plugin. */
export function buildHookLaunchSpec(
  authority: PersistentInstallAuthority,
  platform: string = process.platform,
): HookLaunchSpec {
  const executable = authority.evidence.executable_path;
  const runtime = authority.evidence.runtime_path;
  if (!authority.allowed || !runtime || !executable) {
    throw new Error(
      `persistent hook launch requires resolved Node and CLI paths; authority is ${authority.state}: ${authority.reason}`,
    );
  }
  const args = [executable, HOOK_SUBCOMMAND];
  const command = sessionStartHookCommand(runtime, args, platform);
  return { program: runtime, args, command };
}

function isManagedHook(
  hook: HookEntry | undefined,
  location: "SessionStart" | "session_start",
  matcher: unknown,
): boolean {
  return isOwnedHookCompatibility(
    classifyHookEntry({
      entry: hook,
      location,
      matcher,
      timeoutSeconds: HOOK_TIMEOUT_SECONDS,
    }),
  );
}

/**
 * Pure install updater for the Claude settings.json / Codex hooks.json SessionStart shape —
 * modeled on the SDK's `computeSessionStartHookUpdate`, but recognizing managed hooks through
 * the exact shared compatibility classifier instead of one substring marker. Rewrites the
 * FIRST managed hook in place (preserving its group position), removes any FURTHER managed hooks
 * (a duplicate left by an older marker mismatch), strips legacy `hooks.session_start` managed
 * entries, and appends a fresh group only when no managed hook exists. Returns
 * [updatedSettings, changed]; an already-correct sole managed hook is a no-op. Foreign hooks and
 * groups survive untouched.
 */
export function computeSessionStartHookInstall(
  settings: HookSettings,
  spec: { command: string; timeoutSeconds?: number },
): [HookSettings, boolean] {
  const updated = structuredClone(settings);
  let changed = false;
  if (!updated.hooks) {
    updated.hooks = {};
    changed = true;
  }
  const hooks = updated.hooks;

  if (Array.isArray(hooks.session_start)) {
    const kept = hooks.session_start.filter((h) => !isManagedHook(h, "session_start", undefined));
    if (kept.length !== hooks.session_start.length) {
      changed = true;
      if (kept.length === 0) delete hooks.session_start;
      else hooks.session_start = kept;
    }
  }

  if (!Array.isArray(hooks.SessionStart)) {
    hooks.SessionStart = [];
    changed = true;
  }
  const timeout = spec.timeoutSeconds ?? HOOK_TIMEOUT_SECONDS;
  let rewritten = false;
  const newGroups: typeof hooks.SessionStart = [];
  for (const group of hooks.SessionStart) {
    // `group?.`: a malformed member (null/primitive) passes through untouched, never throws —
    // the CLI install path refuses such files up front (readSettingsForInstall), but this pure
    // updater must stay total for any direct caller.
    if (!Array.isArray(group?.hooks)) {
      newGroups.push(group);
      continue;
    }
    const keptHooks: HookEntry[] = [];
    for (const h of group.hooks) {
      if (!isManagedHook(h, "SessionStart", group.matcher)) {
        keptHooks.push(h);
        continue;
      }
      if (rewritten) {
        changed = true; // a second managed hook is a duplicate — drop it
        continue;
      }
      rewritten = true;
      if (h.command !== spec.command || h.type !== "command" || h.timeout !== timeout) {
        changed = true;
        h.command = spec.command;
        h.type = "command";
        h.timeout = timeout;
      }
      keptHooks.push(h);
    }
    if (keptHooks.length !== group.hooks.length) {
      if (keptHooks.length === 0) continue; // drop the now-empty group
      group.hooks = keptHooks;
    }
    newGroups.push(group);
  }
  hooks.SessionStart = newGroups;
  if (!rewritten) {
    hooks.SessionStart.push({
      matcher: "",
      hooks: [{ type: "command", command: spec.command, timeout }],
    });
    changed = true;
  }
  return changed ? [updated, true] : [settings, false];
}

/**
 * Pure managed-hook removal (the SDK exports none). Removes every SessionStart hook recognized by
 * the exact shared compatibility classifier, drops any group left with no hooks, and
 * strips legacy hooks.session_start matches. Returns [updatedSettings, changed]; unrelated hooks
 * and groups survive untouched. Shared by the Claude settings.json and the Codex hooks.json
 * (identical HookSettings shape).
 */
export function computeHookUninstall(settings: HookSettings): [HookSettings, boolean] {
  const updated = structuredClone(settings);
  let changed = false;
  const hooks = updated.hooks;
  if (!hooks) return [settings, false];

  if (Array.isArray(hooks.session_start)) {
    const kept = hooks.session_start.filter((h) => !isManagedHook(h, "session_start", undefined));
    if (kept.length !== hooks.session_start.length) {
      changed = true;
      if (kept.length === 0) delete hooks.session_start;
      else hooks.session_start = kept;
    }
  }

  if (Array.isArray(hooks.SessionStart)) {
    const newGroups: typeof hooks.SessionStart = [];
    for (const group of hooks.SessionStart) {
      // Tolerate malformed members (skip untouched, never throw) — same reason as install's updater.
      if (!Array.isArray(group?.hooks)) {
        newGroups.push(group);
        continue;
      }
      const keptHooks = group.hooks.filter((h) => !isManagedHook(h, "SessionStart", group.matcher));
      if (keptHooks.length !== group.hooks.length) {
        changed = true;
        if (keptHooks.length === 0) continue; // drop the now-empty group
        newGroups.push({ ...group, hooks: keptHooks });
      } else {
        newGroups.push(group);
      }
    }
    if (changed) hooks.SessionStart = newGroups;
  }

  return changed ? [updated, true] : [settings, false];
}

export interface HookStatus {
  installed: boolean;
  command?: string;
  compatibility: HookCompatibility;
  /** Read-only install preflight result; omitted by the pure compatibility classifier. */
  installSafe?: boolean;
  launchAvailability?: HookLaunchAvailability;
}

/** Pure status scan over the same exact classifier used by install and uninstall. */
export function readHookCompatibilityStatus(settings: HookSettings): HookStatus {
  const hooks = settings.hooks;
  let sawUnmanaged = false;
  const owned: Array<{ command: string; compatibility: HookCompatibility }> = [];
  if (hooks) {
    if (Array.isArray(hooks.SessionStart)) {
      for (const group of hooks.SessionStart) {
        if (!Array.isArray(group?.hooks)) continue; // tolerate malformed members — report, never throw
        for (const h of group.hooks) {
          const compatibility = classifyHookEntry({
            entry: h,
            location: "SessionStart",
            matcher: group.matcher,
            timeoutSeconds: HOOK_TIMEOUT_SECONDS,
          });
          if (isOwnedHookCompatibility(compatibility)) {
            owned.push({ command: h.command!, compatibility });
            continue;
          }
          if (typeof h?.command === "string") sawUnmanaged = true;
        }
      }
    }
    if (Array.isArray(hooks.session_start)) {
      for (const h of hooks.session_start) {
        const compatibility = classifyHookEntry({
          entry: h,
          location: "session_start",
          timeoutSeconds: HOOK_TIMEOUT_SECONDS,
        });
        if (isOwnedHookCompatibility(compatibility)) {
          owned.push({ command: h.command!, compatibility });
          continue;
        }
        if (typeof h?.command === "string") sawUnmanaged = true;
      }
    }
  }
  if (owned.length > 1) {
    return {
      installed: true,
      command: owned[0]!.command,
      compatibility: {
        state: "stale",
        reason: `found ${owned.length} generated hook entries; exactly one is expected`,
        remedy: `re-run \`${distributionBinName()} hook install\` from the durable global npm installation`,
      },
    };
  }
  if (owned.length === 1) {
    return { installed: true, command: owned[0]!.command, compatibility: owned[0]!.compatibility };
  }
  return {
    installed: false,
    compatibility: sawUnmanaged
      ? { state: "unmanaged", reason: "SessionStart entries exist, but none is an exact generated form" }
      : { state: "absent", reason: "no SessionStart command is configured" },
  };
}

/** Stable legacy projection retained for callers that only need installed + command. */
export function readHookStatus(settings: HookSettings): { installed: boolean; command?: string } {
  const status = readHookCompatibilityStatus(settings);
  return status.command === undefined
    ? { installed: status.installed }
    : { installed: status.installed, command: status.command };
}

/** The per-runtime target files for one resolved scope. */
export interface HookTargets {
  claudeSettings: string;
  codexHooks: string;
  codexConfig: string;
  opencodePlugin: string;
  legacyOpencodePlugin: string;
}

function targetsForBase(base: string, platform: string = process.platform): HookTargets {
  const paths = currentHost().paths;
  return {
    claudeSettings: paths.join(base, ".claude", "settings.json"),
    codexHooks: paths.join(base, ".codex", "hooks.json"),
    codexConfig: paths.join(base, ".codex", "config.toml"),
    opencodePlugin: paths.join(base, ".config", "opencode", "plugins", OPENCODE_PLUGIN_FILENAME),
    legacyOpencodePlugin: paths.join(base, ".config", "opencode", "plugins", LEGACY_OPENCODE_PLUGIN_FILENAME),
  };
}

/** Resolve global targets exactly where each host reads them. */
export function globalHookTargets(
  home: string = homedir(),
  env: NodeJS.ProcessEnv = process.env,
  platform: string = process.platform,
): HookTargets {
  const paths = currentHost().paths;
  const claudeHome = resolveHostConfigRoot(HOST_CONFIG_ROOTS.claude, home, env, platform);
  const codexHome = resolveHostConfigRoot(HOST_CONFIG_ROOTS.codex, home, env, platform);
  const opencodeHome = resolveOpenCodeConfigRoot(home, env, platform);
  return {
    claudeSettings: paths.join(claudeHome, "settings.json"),
    codexHooks: paths.join(codexHome, "hooks.json"),
    codexConfig: paths.join(codexHome, "config.toml"),
    opencodePlugin: paths.join(opencodeHome, "plugins", OPENCODE_PLUGIN_FILENAME),
    legacyOpencodePlugin: paths.join(opencodeHome, "plugins", LEGACY_OPENCODE_PLUGIN_FILENAME),
  };
}

export interface HookLocationDeps {
  cwd?: string;
  home?: string;
  env?: NodeJS.ProcessEnv;
  platform?: string;
}

function targetSets(bases: string[] | undefined, deps: HookLocationDeps): HookTargets[] {
  const platform = deps.platform ?? process.platform;
  if (bases !== undefined) return bases.map((base) => targetsForBase(base, platform));
  const cwd = deps.cwd ?? process.cwd();
  const home = deps.home ?? homedir();
  const env = deps.env ?? process.env;
  return [targetsForBase(cwd, platform), globalHookTargets(home, env, platform)];
}

/**
 * Lenient read for the READ-ONLY paths (status, uninstall-scan, needs-update probes): a missing or
 * unparseable file reads as empty settings and is never touched. `hook install` must NOT use this
 * — see {@link readSettingsForInstall}.
 */
function readSettings(path: string): HookSettings {
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf8")) as HookSettings;
  } catch {
    return {};
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Fail-loud read for the INSTALL write path. A missing file is empty settings (we create it), but
 * content we cannot faithfully round-trip — unreadable, unparseable JSON, a non-object root, a
 * non-object `hooks`, a present-but-non-array `hooks.SessionStart`/`hooks.session_start`, or an
 * ARRAY MEMBER that is not the object shape the updater consumes — is refused with a reason
 * instead of being silently normalized: writing "repaired" settings would destroy the user's
 * other keys (permissions, theme, a hand-authored value), and a member the updater cannot walk
 * must refuse UP FRONT rather than throw mid-write.
 */
export function readSettingsForInstall(
  path: string,
): { ok: true; settings: HookSettings } | { ok: false; reason: string } {
  if (!existsSync(path)) return { ok: true, settings: {} };
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch (err) {
    return { ok: false, reason: `unreadable (${err instanceof Error ? err.message : String(err)})` };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    return { ok: false, reason: `unparseable JSON (${err instanceof Error ? err.message : String(err)})` };
  }
  if (!isPlainObject(parsed)) {
    return { ok: false, reason: "settings root is not a JSON object" };
  }
  const hooks = (parsed as HookSettings).hooks;
  if (hooks !== undefined) {
    if (!isPlainObject(hooks)) {
      return { ok: false, reason: "`hooks` is not a JSON object" };
    }
    if (hooks.SessionStart !== undefined) {
      if (!Array.isArray(hooks.SessionStart)) {
        return { ok: false, reason: "`hooks.SessionStart` exists but is not an array" };
      }
      for (const [i, group] of hooks.SessionStart.entries()) {
        if (!isPlainObject(group)) {
          return { ok: false, reason: `\`hooks.SessionStart[${i}]\` is not an object` };
        }
        if (group.hooks !== undefined) {
          if (!Array.isArray(group.hooks)) {
            return { ok: false, reason: `\`hooks.SessionStart[${i}].hooks\` exists but is not an array` };
          }
          for (const [j, entry] of group.hooks.entries()) {
            if (!isPlainObject(entry)) {
              return { ok: false, reason: `\`hooks.SessionStart[${i}].hooks[${j}]\` is not an object` };
            }
          }
        }
      }
    }
    if (hooks.session_start !== undefined) {
      if (!Array.isArray(hooks.session_start)) {
        return { ok: false, reason: "`hooks.session_start` exists but is not an array" };
      }
      for (const [i, entry] of hooks.session_start.entries()) {
        if (!isPlainObject(entry)) {
          return { ok: false, reason: `\`hooks.session_start[${i}]\` is not an object` };
        }
      }
    }
  }
  return { ok: true, settings: parsed as HookSettings };
}

function writeSettings(path: string, settings: HookSettings): void {
  // Match the SDK's on-disk format: 2-space JSON + trailing newline.
  atomicWriteFileSync(path, `${JSON.stringify(settings, null, 2)}\n`);
}

/**
 * The OpenCode ambient-context plugin source — OURS, not the SDK's generated one (the SDK plugin
 * spawns its command with an EMPTY argv, so it cannot run `<bin> session-start`). Functionally a
 * fork of the SDK's plugin with an args array. Line 1 remains SDK-marker compatible, but this
 * command's status/install/uninstall paths require byte-exact regeneration before claiming it.
 */
function buildOpenCodePluginTemplate(options: {
  program: string;
  commandArgs?: string[];
  timeoutSeconds: number;
  marker: string;
  managedMarker: string;
  exportName: string;
  generatedComment: string;
  runFunction: "runAxiSessionStart" | "runAxiHomeView";
}): string {
  const argsDeclaration = options.commandArgs === undefined
    ? ""
    : `const commandArgs = ${JSON.stringify(options.commandArgs)};\n`;
  const spawnArgs = options.commandArgs === undefined ? "[]" : "commandArgs";
  return `// ${options.managedMarker}
${options.generatedComment}
import { spawn } from "node:child_process";

const command = ${JSON.stringify(options.program)};
${argsDeclaration}const marker = ${JSON.stringify(options.marker)};
const ambientHeader = ${JSON.stringify(`## AXI ambient context: ${options.marker}`)};
const timeoutMs = ${JSON.stringify(options.timeoutSeconds * 1000)};

function ${options.runFunction}(cwd) {
  return new Promise((resolve) => {
    const child = spawn(command, ${spawnArgs}, {
      cwd: directoryOrFallback(cwd),
      env: process.env,
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      child.kill("SIGTERM");
      resolve("error: " + marker + " ambient context timed out after " + timeoutMs + "ms");
    }, timeoutMs);

    child.stdout?.setEncoding("utf-8");
    child.stderr?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve("error: " + marker + " ambient context failed: " + error.message);
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code === 0) {
        resolve(stdout.trim());
        return;
      }
      const message = (stderr || stdout || marker + " exited with code " + code).trim();
      resolve("error: " + marker + " ambient context failed: " + message);
    });
  });
}

function directoryOrFallback(directory) {
  return typeof directory === "string" && directory.length > 0
    ? directory
    : process.cwd();
}

export const ${options.exportName} = async ({ directory }) => {
  const sessionCache = new Map();

  return {
    "experimental.chat.system.transform": async (input, output) => {
      const sessionID = input.sessionID ?? "__global__";
      let homeView = sessionCache.get(sessionID);
      if (homeView === undefined) {
        homeView = await ${options.runFunction}(directory);
        sessionCache.set(sessionID, homeView);
      }

      if (homeView.length === 0) return;
      output.system.push(ambientHeader + "\\n" + homeView);
    },
  };
};
`;
}

export function buildOpenCodePluginSource(
  program: string,
  commandArgs: string[] = [HOOK_SUBCOMMAND],
  timeoutSeconds: number = HOOK_TIMEOUT_SECONDS,
): string {
  return buildOpenCodePluginTemplate({
    program,
    commandArgs,
    timeoutSeconds,
    marker: HOOK_MARKER,
    managedMarker: OPENCODE_MANAGED_MARKER,
    exportName: "AxiSuperbeeAmbientContextPlugin",
    generatedComment:
      "// Generated by `superbee hook install` (axi-sdk-js managed-marker compatible). It is safe\n" +
      "// to edit only if you remove the managed marker above.",
    runFunction: "runAxiSessionStart",
  });
}

/** Byte-for-byte reconstruction of the last ASLite args-aware generator. */
function buildLegacyOpenCodePluginSource(
  program: string,
  commandArgs: string[] = [HOOK_SUBCOMMAND],
  timeoutSeconds: number = HOOK_TIMEOUT_SECONDS,
): string {
  return buildOpenCodePluginTemplate({
    program,
    commandArgs,
    timeoutSeconds,
    marker: LEGACY_HOOK_MARKER,
    managedMarker: LEGACY_OPENCODE_MANAGED_MARKER,
    exportName: "AxiAgentstateLiteAmbientContextPlugin",
    generatedComment:
      "// Generated by `superbee hook install` (axi-sdk-js managed-marker compatible). It is safe\n" +
      "// to edit only if you remove the managed marker above.",
    runFunction: "runAxiSessionStart",
  });
}

/** Byte-for-byte reconstruction of the published @holaxis/aslite pre.3 args-aware generator. */
function buildPublishedAsliteOpenCodePluginSource(
  program: string,
): string {
  return buildOpenCodePluginTemplate({
    program,
    commandArgs: [HOOK_SUBCOMMAND],
    timeoutSeconds: HOOK_TIMEOUT_SECONDS,
    marker: LEGACY_HOOK_MARKER,
    managedMarker: LEGACY_OPENCODE_MANAGED_MARKER,
    exportName: "AxiAgentstateLiteAmbientContextPlugin",
    generatedComment:
      "// Generated by `agentstate-lite hook install` (axi-sdk-js managed-marker compatible). It is safe\n" +
      "// to edit only if you remove the managed marker above.",
    runFunction: "runAxiSessionStart",
  });
}

function isPublishedAsliteOpenCodeProgram(program: string): boolean {
  if (program === "aslite" || program === "agentstate-lite") return true;
  if (!isAbsolute(program)) return false;
  const portable = normalize(program).split(sep).join("/");
  return /\/node_modules\/@holaxis\/aslite\/dist\/agentstate-lite\.mjs$/.test(portable);
}

/** Byte-for-byte reconstruction of the pre-argv axi-sdk-js generator for safe legacy ownership. */
function buildLegacySdkOpenCodePluginSource(command: string, timeoutSeconds: number): string {
  return buildOpenCodePluginTemplate({
    program: command,
    timeoutSeconds,
    marker: LEGACY_HOOK_MARKER,
    managedMarker: LEGACY_OPENCODE_MANAGED_MARKER,
    exportName: "AxiAgentstateLiteAmbientContextPlugin",
    generatedComment:
      "// This file is generated by axi-sdk-js. It is safe to edit only if you remove the managed marker above.",
    runFunction: "runAxiHomeView",
  });
}

interface OpenCodeHookStatus {
  installed: boolean;
  compatibility: HookCompatibility;
  command?: string;
  launchAvailability?: HookLaunchAvailability;
}

function generatedConstant(source: string, name: string): unknown {
  const match = source.match(new RegExp(`^const ${name} = (.+);$`, "m"));
  if (!match) return undefined;
  try {
    return JSON.parse(match[1]!);
  } catch {
    return undefined;
  }
}

/** Git may materialize a generated JS fixture with CRLF on Windows; line endings are not authorship. */
function normalizedGeneratedSource(source: string): string {
  return source.replaceAll("\r\n", "\n");
}

/** Exact-source classifier: a marker or familiar substring alone never authorizes mutation. */
function readOpenCodeHookStatus(path: string, expectedSource?: string): OpenCodeHookStatus {
  let entry: ReturnType<typeof lstatSync>;
  try {
    entry = lstatSync(path);
  } catch {
    return { installed: false, compatibility: { state: "absent", reason: "plugin file is absent" } };
  }
  if (entry.isSymbolicLink()) {
    return {
      installed: false,
      compatibility: {
        state: "unmanaged",
        reason: "plugin path is a symlink; generated-plugin ownership requires a regular file",
      },
    };
  }
  if (!entry.isFile()) {
    return { installed: false, compatibility: { state: "unmanaged", reason: "plugin path is not a regular file" } };
  }
  const read = readRegularFileTextNoFollowSync(path);
  if (read.state === "missing") {
    return { installed: false, compatibility: { state: "absent", reason: "plugin file is absent" } };
  }
  if (read.state === "unsafe") {
    return { installed: false, compatibility: { state: "unmanaged", reason: "plugin file is unreadable" } };
  }
  const source = read.text;
  const comparableSource = normalizedGeneratedSource(source);
  if (expectedSource !== undefined && comparableSource === normalizedGeneratedSource(expectedSource)) {
    const program = generatedConstant(source, "command");
    const args = generatedConstant(source, "commandArgs");
    return {
      installed: true,
      compatibility: { state: "current", reason: "plugin exactly matches this installation's generator" },
      ...(typeof program === "string" && Array.isArray(args) && args.every((arg) => typeof arg === "string")
        ? { command: [program, ...args].map((token) => renderGeneratedHookToken(token)).join(" ") }
        : {}),
    };
  }

  const command = generatedConstant(source, "command");
  const timeoutMs = generatedConstant(source, "timeoutMs");
  const args = generatedConstant(source, "commandArgs");
  if (
    typeof command === "string" &&
    Array.isArray(args) &&
    args.every((arg) => typeof arg === "string") &&
    typeof timeoutMs === "number" &&
    Number.isInteger(timeoutMs) &&
    comparableSource === buildOpenCodePluginSource(command, args as string[], timeoutMs / 1000)
  ) {
    const launchCommand = [command, ...(args as string[])].map((token) => renderGeneratedHookToken(token)).join(" ");
    const compatibility = classifyHookCommand(launchCommand);
    if (!isOwnedHookCompatibility(compatibility)) return { installed: false, compatibility };
    if (timeoutMs !== HOOK_TIMEOUT_SECONDS * 1000) {
      return {
        installed: true,
        command: launchCommand,
        compatibility: {
          state: "stale",
          reason: "recognized generated plugin has a non-current timeout",
          remedy: `re-run \`${distributionBinName()} hook install\` from the durable global npm installation`,
        },
      };
    }
    return { installed: true, compatibility, command: launchCommand };
  }

  if (
    typeof command === "string" &&
    Array.isArray(args) &&
    args.every((arg) => typeof arg === "string") &&
    typeof timeoutMs === "number" &&
    Number.isInteger(timeoutMs) &&
    (
      comparableSource === buildLegacyOpenCodePluginSource(command, args as string[], timeoutMs / 1000)
      || (
        args.length === 1
        && args[0] === HOOK_SUBCOMMAND
        && timeoutMs === HOOK_TIMEOUT_SECONDS * 1000
        && isPublishedAsliteOpenCodeProgram(command)
        && comparableSource === buildPublishedAsliteOpenCodePluginSource(command)
      )
    )
  ) {
    const compatibility = classifyHookCommand(
      [command, ...(args as string[])].map((token) => renderGeneratedHookToken(token)).join(" "),
    );
    if (!isOwnedHookCompatibility(compatibility)) return { installed: false, compatibility };
    return {
      installed: true,
      compatibility: {
        state: timeoutMs === HOOK_TIMEOUT_SECONDS * 1000 ? "legacy_identity" : "stale",
        reason: "recognized generated OpenCode plugin uses the legacy ASLite identity",
        remedy: `re-run \`${distributionBinName()} hook install\` from the durable global npm installation`,
      },
    };
  }

  if (
    typeof command === "string" &&
    args === undefined &&
    typeof timeoutMs === "number" &&
    Number.isInteger(timeoutMs) &&
    comparableSource === buildLegacySdkOpenCodePluginSource(command, timeoutMs / 1000) &&
    isOwnedHookCompatibility(classifyHookCommand(command))
  ) {
    return {
      installed: true,
      compatibility: {
        state: "stale",
        reason: "recognized pre-session-start axi-sdk-js plugin",
        remedy: `re-run \`${distributionBinName()} hook install\` from the durable global npm installation`,
      },
    };
  }

  return {
    installed: false,
    compatibility: {
      state: "unmanaged",
      reason: "plugin file does not exactly match a known generated source",
    },
  };
}

function readOpenCodeTargetsStatus(
  targets: HookTargets,
  expectedSource?: string,
): OpenCodeHookStatus {
  const canonical = readOpenCodeHookStatus(targets.opencodePlugin, expectedSource);
  const legacy = readOpenCodeHookStatus(targets.legacyOpencodePlugin);
  const owned = [canonical, legacy].filter((status) => status.installed);
  if (owned.length > 1) {
    return {
      installed: true,
      compatibility: {
        state: "stale",
        reason: "found both canonical and legacy generated OpenCode plugins; exactly one is expected",
        remedy: `re-run \`${distributionBinName()} hook install\` from the durable global npm installation`,
      },
    };
  }
  if (owned.length === 1) return owned[0]!;
  if (
    canonical.compatibility.state === "unmanaged" ||
    legacy.compatibility.state === "unmanaged"
  ) {
    return {
      installed: false,
      compatibility: {
        state: "unmanaged",
        reason: "OpenCode plugin files exist, but none is an exact generated form",
      },
    };
  }
  return canonical;
}

function openCodeClaimPath(path: string): string {
  return `${path}.claim-${process.pid}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function restoreOpenCodeClaim(claim: string, path: string): void {
  try {
    const entry = lstatSync(claim);
    if (entry.isSymbolicLink()) symlinkSync(readlinkSync(claim), path);
    else if (entry.isFile()) linkSync(claim, path);
    else throw new Error("claimed entry is not a regular file or symlink");
  } catch (error) {
    throw new Error(`OpenCode plugin changed during migration; recovery copy retained at ${collapseHomeDirectory(claim)}`, { cause: error });
  }
  rmSync(claim, { force: true });
}

/** Atomically isolate the current directory entry, then establish ownership on the isolated bytes. */
function claimOwnedOpenCodePlugin(path: string): string | undefined {
  const inspected = readOpenCodeHookStatus(path);
  if (!inspected.installed) return undefined;
  const claim = openCodeClaimPath(path);
  try {
    renameSync(path, claim);
  } catch (error) {
    throw new Error("OpenCode plugin changed after inspection; nothing was removed", { cause: error });
  }
  const claimed = readOpenCodeHookStatus(claim);
  if (!claimed.installed) {
    restoreOpenCodeClaim(claim, path);
    throw new Error("OpenCode plugin changed after inspection; the changed bytes were preserved");
  }
  return claim;
}

function removeOwnedOpenCodePlugin(path: string): boolean {
  const claim = claimOwnedOpenCodePlugin(path);
  if (claim === undefined) return false;
  rmSync(claim, { force: true });
  return true;
}

function installOpenCodePlugin(path: string, next: string): boolean {
  const inspected = readOpenCodeHookStatus(path, next);
  if (inspected.compatibility.state === "unmanaged") {
    throw new Error("refusing to overwrite unmanaged OpenCode plugin");
  }
  if (inspected.compatibility.state === "current") return false;

  const claim = inspected.installed ? claimOwnedOpenCodePlugin(path) : undefined;
  try {
    atomicWriteFileSync(path, next, {
      followFinalSymlink: false,
      expected: {
        destination: null,
        content: null,
        parent: capturePrivateConfigParent(path),
      },
    });
  } catch (error) {
    if (claim !== undefined) restoreOpenCodeClaim(claim, path);
    throw error;
  }
  if (claim !== undefined) rmSync(claim, { force: true });
  return true;
}

/**
 * Re-install prompt signal (consumed by the home render): TRUE when a MANAGED
 * SessionStart hook is installed at any of the given scope bases (default: the cwd project scope
 * and each host's configured global target) whose command predates {@link HOOK_SUBCOMMAND} — i.e. the
 * former home-only hook. Fs-only reads, tolerant of anything malformed; self-clearing (a re-run
 * `hook install` rewrites the command and this goes quiet).
 */
export function hookNeedsUpdate(bases?: string[], deps: HookLocationDeps = {}): boolean {
  for (const targets of targetSets(bases, deps)) {
    for (const p of [targets.claudeSettings, targets.codexHooks]) {
      const s = readHookCompatibilityStatus(readSettings(p));
      if (s.installed && s.compatibility.state !== "current") return true;
    }
    const opencode = readOpenCodeTargetsStatus(targets);
    if (opencode.installed && opencode.compatibility.state !== "current") return true;
  }
  return false;
}

/**
 * True when ANY managed SessionStart hook is installed at any of the given scope bases (default:
 * the cwd project scope and each host's configured global target) — Claude Code settings, Codex hooks, or
 * the OpenCode plugin. Fs-only reads, tolerant of anything malformed. This is the onboarding
 * last-mile signal sync's receipt hints on: no hook anywhere means new sessions never see the
 * board until someone runs `hook install`. (Contrast {@link hookNeedsUpdate}: installed but
 * PREDATING `session-start` — a different, self-clearing prompt on the home render.)
 */
export function hookInstalled(bases?: string[], deps: HookLocationDeps = {}): boolean {
  for (const targets of targetSets(bases, deps)) {
    for (const p of [targets.claudeSettings, targets.codexHooks]) {
      if (readHookCompatibilityStatus(readSettings(p)).installed) return true;
    }
    if (readOpenCodeTargetsStatus(targets).installed) return true;
  }
  return false;
}

/** Injectable filesystem-location and output seams, defaulting to production. */
export interface HookDeps extends HookLocationDeps {
  /** Override all scope targets with one legacy base directory (for focused tests). */
  base: string;
  /** Legacy test seam for one direct command base; production uses install authority. */
  commandBase: string;
  /** Override the complete launch spec (tests). */
  launchSpec: HookLaunchSpec;
  /** Override the one pre-write persistent-install authority (tests). */
  installAuthority: () => PersistentInstallAuthority;
  stdout: (s: string) => void;
}

export interface HookStatusInspection {
  targets: HookTargets;
  hosts: {
    claude_code: HookStatus;
    codex: HookStatus;
    opencode: OpenCodeHookStatus;
  };
  displayCommand?: string;
}

/** Read all supported hook hosts through the same exact classifiers as `hook status`. */
export function inspectHookStatus(
  scope: InstallScope,
  deps: Partial<HookDeps> = {},
): HookStatusInspection {
  const targets = deps.base !== undefined
    ? targetsForBase(deps.base, deps.platform)
    : scope === "user"
      ? globalHookTargets(deps.home ?? homedir(), deps.env ?? process.env, deps.platform)
      : targetsForBase(deps.cwd ?? process.cwd(), deps.platform);
  let expectedLaunch = deps.launchSpec;
  try {
    if (!expectedLaunch && deps.commandBase !== undefined) {
      expectedLaunch = {
        program: deps.commandBase,
        args: [HOOK_SUBCOMMAND],
        command: sessionStartHookCommand(deps.commandBase, [HOOK_SUBCOMMAND], deps.platform),
      };
    }
  } catch {
    expectedLaunch = undefined;
  }
  const inspectSettingsTarget = (path: string): HookStatus => {
    const status = readHookCompatibilityStatus(readSettings(path));
    const launchAvailability = inspectHookLaunchAvailability(status.command);
    const preflight = readSettingsForInstall(path);
    if (!preflight.ok) {
      return { ...status, installSafe: false, launchAvailability };
    }
    return { ...status, installSafe: true, launchAvailability };
  };
  const claude = inspectSettingsTarget(targets.claudeSettings);
  const codex = inspectSettingsTarget(targets.codexHooks);
  const opencode = readOpenCodeTargetsStatus(
    targets,
    expectedLaunch
      ? buildOpenCodePluginSource(expectedLaunch.program, expectedLaunch.args)
      : undefined,
  );
  opencode.launchAvailability = inspectHookLaunchAvailability(opencode.command);
  return {
    targets,
    hosts: { claude_code: claude, codex, opencode },
    ...(claude.command ?? expectedLaunch?.command
      ? { displayCommand: claude.command ?? expectedLaunch?.command }
      : {}),
  };
}

/**
 * CLI entry: dispatch the positional subcommand (install|status|uninstall). Output is TOON. An
 * unknown/missing subcommand, or an unsupported --scope, is a USAGE error.
 */
export async function hook(argv: string[], deps: Partial<HookDeps> = {}): Promise<void> {
  const stdout = deps.stdout ?? ((s: string) => void process.stdout.write(s));

  const { values, selection } = parseSelectorOrUsage(
    () =>
      parseArgs({
        args: argv,
        options: {
          scope: { type: "string" },
          "turn-end-sync": { type: "boolean" },
          "git-boards": { type: "boolean" },
          json: { type: "boolean" },
          help: { type: "boolean", short: "h" },
        },
        allowPositionals: true,
      }),
    "hook",
    (positionals) => {
      const [sub, ...data] = positionals;
      if (sub === undefined) return { kind: "unknown" } as const;
      if (sub !== "install" && sub !== "status" && sub !== "uninstall") return { kind: "unknown", token: sub } as const;
      return {
        kind: "selected",
        leaf: sub === "install"
          ? CLI_LEAVES.hookInstall
          : sub === "status"
            ? CLI_LEAVES.hookStatus
            : CLI_LEAVES.hookUninstall,
        data,
        payload: sub,
      } as const;
    },
  );
  if (selection.kind === "help" || selection.kind === "navigation") {
    stdout(renderUsage(HOOK_USAGE));
    return;
  }

  if (selection.kind === "unknown") {
    throw new CliError(
      "USAGE",
      selection.token === undefined
        ? "hook requires a subcommand (install|status|uninstall)"
        : `unknown hook subcommand: ${selection.token} (expected install|status|uninstall)`,
      { help: `${cliInvocation()} hook install|status|uninstall [--scope project|user]` },
    );
  }
  const sub = selection.payload;

  const requestedScope = values.scope as string | undefined;
  const scope = normalizeInstallScope(requestedScope);
  if (scope === undefined) {
    throw new CliError("USAGE", `unsupported hook scope: ${requestedScope} (expected project|user)`, {
      help: `${cliInvocation()} hook ${sub} --scope project|user`,
    });
  }

  const mode = resolveMode(values);
  const turnEndSync = values["turn-end-sync"] === true;
  if (turnEndSync && sub === "status") {
    throw new CliError("USAGE", "--turn-end-sync applies to hook install and hook uninstall; status always reports it", {
      help: `${cliInvocation()} hook status`,
    });
  }
  const gitBoards = values["git-boards"] === true;
  if (gitBoards && (sub !== "install" || !turnEndSync)) {
    throw new CliError("USAGE", "--git-boards applies only to hook install --turn-end-sync", {
      help: `${cliInvocation()} hook install --turn-end-sync --git-boards`,
    });
  }

  if (sub === "status") {
    const inspection = inspectHookStatus(scope, deps);
    const { claude_code: claude, codex, opencode } = inspection.hosts;
    stdout(
      render(
        {
          hook: {
            action: "status",
            scope,
            installed: claude.installed || codex.installed || opencode.installed,
            claude_code: claude.installed,
            codex: codex.installed,
            opencode: opencode.installed,
            turn_end_sync: turnEndStatus(readSettings(inspection.targets.claudeSettings), readSettings(inspection.targets.codexHooks)),
            ...(inspection.displayCommand !== undefined ? { command: inspection.displayCommand } : {}),
            hosts: {
              claude_code: {
                path: collapseHomeDirectory(inspection.targets.claudeSettings),
                state: claude.launchAvailability?.state === "unavailable" ? "unavailable" : claude.compatibility.state,
                compatibility: claude.compatibility,
                launchAvailability: claude.launchAvailability,
              },
              codex: {
                path: collapseHomeDirectory(inspection.targets.codexHooks),
                state: codex.launchAvailability?.state === "unavailable" ? "unavailable" : codex.compatibility.state,
                compatibility: codex.compatibility,
                launchAvailability: codex.launchAvailability,
              },
              opencode: {
                path: collapseHomeDirectory(inspection.targets.opencodePlugin),
                state: opencode.launchAvailability?.state === "unavailable" ? "unavailable" : opencode.compatibility.state,
                compatibility: opencode.compatibility,
                launchAvailability: opencode.launchAvailability,
              },
            },
            targets: {
              claude_code: collapseHomeDirectory(inspection.targets.claudeSettings),
              codex: collapseHomeDirectory(inspection.targets.codexHooks),
              opencode: collapseHomeDirectory(inspection.targets.opencodePlugin),
            },
          },
        },
        mode,
      ),
    );
    return;
  }

  const targets = deps.base !== undefined
    ? targetsForBase(deps.base, deps.platform)
    : scope === "user"
      ? globalHookTargets(deps.home ?? homedir(), deps.env ?? process.env, deps.platform)
      : targetsForBase(deps.cwd ?? process.cwd(), deps.platform);

  if (sub === "install") {
    // Every host that was not installed becomes a structured refusal; the command never emits a
    // success receipt that hides a malformed or unmanaged target.
    const refusals: string[] = [];
    const failTarget = (target: string, err: unknown) =>
      refusals.push(
        `${collapseHomeDirectory(target)}: ${err instanceof Error ? err.message : String(err)} — this target was not installed`,
      );
    // Resolve and validate the one launch BEFORE touching any target. Production npm installs
    // must prove a durable global layout; the command then binds stable prefix paths explicitly.
    let launch: HookLaunchSpec;
    let authority: PersistentInstallAuthority | undefined;
    try {
      if (deps.launchSpec) {
        launch = deps.launchSpec;
      } else if (deps.commandBase !== undefined) {
        launch = {
          program: deps.commandBase,
          args: [HOOK_SUBCOMMAND],
          command: sessionStartHookCommand(deps.commandBase, [HOOK_SUBCOMMAND], deps.platform),
        };
      } else {
        authority =
          deps.installAuthority?.() ?? resolvePersistentInstallAuthority({
            env: deps.env ?? process.env,
            platform: deps.platform,
          });
        if (!authority.allowed) {
          throw new Error(
            `persistent hook install requires a durable npm-global CLI; authority is ${authority.state}: ${authority.reason}`,
          );
        }
        launch = buildHookLaunchSpec(authority, deps.platform);
      }
      if (!isManagedHookCommand(launch.command, deps.platform)) {
        throw new Error(
          `composed hook command ${JSON.stringify(launch.command)} would not be recognized as managed — refusing to install an orphan hook`,
        );
      }
    } catch (err) {
      throw new CliError("RUNTIME", err instanceof Error ? err.message : String(err), {
        ...(authority ? { details: { install_authority: authority } } : {}),
        help: `run npm install -g ${distributionPackageName()}, verify ${distributionBinName()} version --json, then re-run hook install; npx remains supported for read-only/trial commands`,
      });
    }
    const command = launch.command;
    const stopHosts: IntegrationHost[] = [];
    const gitStopHosts: IntegrationHost[] = [];
    const changedByHost: Partial<Record<IntegrationHost, boolean>> = {};
    // Claude Code settings.json + Codex hooks.json: OUR SDK-modeled pure updater, recognizing
    // both managed command forms (see the module header for why the SDK's marker cannot).
    for (const [host, target] of [
      ["claude_code", targets.claudeSettings],
      ["codex", targets.codexHooks],
    ] as const) {
      try {
        const read = readSettingsForInstall(target);
        if (!read.ok) {
          refusals.push(`${collapseHomeDirectory(target)}: ${read.reason} — nothing was written to this file`);
          continue;
        }
        let [updated, changed] = computeSessionStartHookInstall(read.settings, {
          command,
          timeoutSeconds: HOOK_TIMEOUT_SECONDS,
        });
        // An installed Stop hook is kept current by every install; only the flag adds one.
        const wantsStop = turnEndSync || turnEndHookInstalled(read.settings);
        let withGit = false;
        if (wantsStop) {
          const problem = stopShapeProblem(updated);
          if (problem) {
            refusals.push(`${collapseHomeDirectory(target)}: ${problem} — nothing was written to this file`);
            continue;
          }
          // The flag sets the Git opt-in; a plain reinstall keeps what this file already has.
          withGit = turnEndSync ? gitBoards : turnEndHookSyncsGitBoards(read.settings, deps.platform);
          const [withStop, stopChanged] = computeTurnEndHookInstall(updated, {
            command: turnEndHookCommand(launch, deps.platform, { gitBoards: withGit }),
            timeoutSeconds: TURN_END_HOOK_TIMEOUT_SECONDS,
          });
          updated = withStop;
          changed = changed || stopChanged;
        }
        if (changed) writeSettings(target, updated);
        if (wantsStop) stopHosts.push(host);
        if (wantsStop && withGit) gitStopHosts.push(host);
        changedByHost[host] = changed;
      } catch (err) {
        failTarget(target, err);
      }
    }
    // Codex [features].hooks flag (config.toml) — same SDK updater the old installer used.
    const codexConfigPath = targets.codexConfig;
    try {
      const current = existsSync(codexConfigPath) ? readFileSync(codexConfigPath, "utf8") : "";
      const [updated, changed] = computeCodexConfigUpdate(current);
      if (changed) atomicWriteFileSync(codexConfigPath, updated);
      changedByHost.codex = changedByHost.codex === true || changed;
    } catch (err) {
      failTarget(codexConfigPath, err);
    }
    // OpenCode ambient-context plugin — our args-aware source, SDK-marker compatible.
    try {
      const next = buildOpenCodePluginSource(launch.program, launch.args);
      const currentStatus = readOpenCodeHookStatus(targets.opencodePlugin, next);
      if (currentStatus.compatibility.state === "unmanaged") {
        refusals.push(`${collapseHomeDirectory(targets.opencodePlugin)}: refusing to overwrite unmanaged OpenCode plugin`);
      } else {
        const installed = installOpenCodePlugin(targets.opencodePlugin, next);
        const removedLegacy = removeOwnedOpenCodePlugin(targets.legacyOpencodePlugin);
        changedByHost.opencode = installed || removedLegacy;
      }
    } catch (err) {
      failTarget(targets.opencodePlugin, err);
    }
    if (refusals.length > 0) {
      throw new CliError(
        "RUNTIME",
        `hook install failed for ${refusals.length} target(s); other targets were still processed`,
        {
          details: { refused: refusals },
          help: "fix or remove the named file(s), then re-run hook install",
        },
      );
    }
    const lifecycle = integrationChangeReceipt(changedByHost);
    const out: Record<string, unknown> = {
      action: "install",
      scope,
      installed: true,
      command,
      turn_end_sync: stopHosts.length > 0
        ? {
            installed: true,
            hosts: stopHosts,
            command: turnEndHookCommand(launch, deps.platform, { gitBoards: gitStopHosts.length > 0 }),
            ...(gitStopHosts.length > 0 ? { git_boards: gitStopHosts } : {}),
            opt_out: `${cliInvocation()} hook uninstall --turn-end-sync`,
          }
        : { installed: false, opt_in: `${cliInvocation()} hook install --turn-end-sync` },
      ...lifecycle,
      targets: {
        claude_code: collapseHomeDirectory(targets.claudeSettings),
        codex: collapseHomeDirectory(targets.codexHooks),
        opencode: collapseHomeDirectory(targets.opencodePlugin),
      },
    };
    stdout(render({ hook: out }, mode));
    return;
  }

  // uninstall: remove the managed hook from the JSON targets + delete the OpenCode plugin file. The
  // Codex config.toml [features].hooks flag is left in place (harmless; other hooks may rely on it).
  let changed = false;
  const notes: string[] = [];
  for (const path of [targets.claudeSettings, targets.codexHooks]) {
    const settings = readSettings(path);
    const [withoutSessionStart, sessionStartChanged] = turnEndSync ? [settings, false] : computeHookUninstall(settings);
    const [updated, stopChanged] = computeTurnEndHookUninstall(withoutSessionStart);
    if (sessionStartChanged || stopChanged) {
      writeSettings(path, updated);
      changed = true;
    }
  }
  if (turnEndSync) {
    stdout(
      render(
        {
          hook: {
            action: "uninstall",
            scope,
            turn_end_sync: { installed: false },
            changed,
            targets: { claude_code: collapseHomeDirectory(targets.claudeSettings), codex: collapseHomeDirectory(targets.codexHooks) },
          },
        },
        mode,
      ),
    );
    return;
  }
  for (const path of [targets.opencodePlugin, targets.legacyOpencodePlugin]) {
    const openCodeStatus = readOpenCodeHookStatus(path);
    if (openCodeStatus.installed) {
      changed = removeOwnedOpenCodePlugin(path) || changed;
    } else if (openCodeStatus.compatibility.state === "unmanaged") {
      notes.push(`preserved unmanaged OpenCode plugin: ${collapseHomeDirectory(path)}`);
    }
  }
  stdout(
    render(
      {
        hook: {
          action: "uninstall",
          scope,
          installed: false,
          changed,
          ...(notes.length > 0 ? { notes } : {}),
          targets: {
            claude_code: collapseHomeDirectory(targets.claudeSettings),
            codex: collapseHomeDirectory(targets.codexHooks),
            opencode: collapseHomeDirectory(targets.opencodePlugin),
          },
        },
      },
      mode,
    ),
  );
}
