import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { isMainModule } from "../../../scripts/is-main-module.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, "..");
const generatedDir = join(packageRoot, "src/generated");
const resources = [
  {
    source: "view",
    marker: "<!-- ASLITE_MCP_APP_SCRIPT -->",
    generatedFile: "view-html.generated.ts",
    exportName: "MCP_VIEW_HTML",
    label: "View",
  },
  {
    source: "document",
    marker: "<!-- SUPERBEE_DOCUMENT_APP_SCRIPT -->",
    generatedFile: "document-html.generated.ts",
    exportName: "MCP_DOCUMENT_HTML",
    label: "document reader",
  },
];

/**
 * Bundle the fixed MCP App shell into one self-contained HTML resource. The npm CLI inlines the
 * generated TypeScript string into its existing single-file artifact, so the installed command has
 * no adjacent asset lookup and no runtime dependency resolution.
 */
async function buildResource(resource) {
  const [template, result] = await Promise.all([
    readFile(join(packageRoot, `src/${resource.source}.html`), "utf8"),
    build({
      entryPoints: [join(packageRoot, `src/${resource.source}.ts`)],
      bundle: true,
      platform: "browser",
      format: "iife",
      target: "es2022",
      minify: true,
      write: false,
      logLevel: "silent",
    }),
  ]);
  const javascript = result.outputFiles?.[0]?.text;
  if (!javascript) throw new Error(`MCP App ${resource.label} build produced no JavaScript`);
  // Use a replacement FUNCTION: bundled dependency code legitimately contains `$`` / `$'`
  // sequences, which String.replace interprets as replacement tokens when passed as a string.
  // That silently splices template bytes into the JavaScript and produces invalid HTML.
  const html = template.replace(
    resource.marker,
    () => `<script>${javascript.replaceAll("</script", "<\\/script")}</script>`,
  );
  if (html === template) {
    throw new Error(`MCP App ${resource.label} template is missing its script marker`);
  }

  await mkdir(generatedDir, { recursive: true });
  await writeFile(
    join(generatedDir, resource.generatedFile),
    `// AUTO-GENERATED by packages/mcp-app/scripts/build-view.mjs — DO NOT EDIT.\n` +
      `export const ${resource.exportName} = ${JSON.stringify(html)};\n`,
  );
  process.stdout.write(
    `built MCP App ${resource.label} (${Buffer.byteLength(html, "utf8")} bytes)\n`,
  );
  return html;
}

export async function buildMcpViewHtml() {
  const built = [];
  for (const resource of resources) built.push(await buildResource(resource));
  return built[0];
}

function parseBuildViewArgs(argv) {
  if (argv.length !== 0) throw new Error("usage: build-view.mjs");
}

async function main(argv = process.argv.slice(2)) {
  parseBuildViewArgs(argv);
  await buildMcpViewHtml();
}

if (isMainModule(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = error instanceof Error && error.message === "usage: build-view.mjs" ? 2 : 1;
  });
}
